spring:
  application:
    name: learning-graphql
  flyway:
    enabled: false
  graphql:
    graphiql:
      enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/test_db
    username: test_user
    password: test_password
  jooq:
    sql-dialect: Postgres
