version: '3.8'

services:
  postgres-temp:
    image: postgres:latest
    container_name: postgres-temp-container
    restart: "no"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=test_db
      - POSTGRES_USER=test_user
      - POSTGRES_PASSWORD=test_password